// <auto-generated />
namespace MovieBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class March7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(March7));
        
        string IMigrationMetadata.Id
        {
            get { return "202103070831175_March7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
