// <auto-generated />
namespace MovieBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MovieFebruary12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieFebruary12));
        
        string IMigrationMetadata.Id
        {
            get { return "202102130319447_Movie-February12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
